{ pkgs }:

with pkgs; [
          act
          awscli2
          azure-cli
          bat
          buf
          cargo
          cilium-cli
          colima
          coreutils
          crossplane
          deno
          desktoppr
          devenv
          direnv
          docker
          docker-slim
          dyff
          entr
          eza
          fd
          firefox
          flyctl
          fzf
          gh
          git
          gnumake
          gnupg
          gnutls
          go
          go-task
          go-tools
          golangci-lint
          gopls
          goreleaser
          gotestsum
          grpcurl
          jj
          jq
          k6
          ko
          k9s
          kind
          kubebuilder
          kubectl
          # kubelogin not building - RATELIMIT?
          kustomize
          kyverno
          lazygit
          libpq
          lima
          lua
          lua-language-server
          luarocks
          mkcert
          neovim
          nmap
          nodejs
          nushell
          openssh
          packer
          pinentry_mac
          protobuf
          qemu
          ripgrep
          ripsecrets
          sniffnet
          sops
          starship
          step-cli
          tailwindcss
          talosctl
          templ
          tree
          tree-sitter
          unbound
          utm
          watch
          wezterm
          wget
          yq
          yubikey-manager
          zoxide
          zsh
          zstd
      ]
