return {
	-- "markview",
	-- before = function()
	-- 	LZN.trigger_load("nvim-web-devicons")
	-- end,
	-- lazy = false,
	-- ft = { "markdown" },
	-- after = function()
	-- 	require("markview").setup({
	-- 		preview = {
	-- 			enable = true,
	-- 			icon_provider = "devicons",
	-- 		},
	-- 	})
	-- end,
	-- keys = {
	-- 	{
	-- 		"<leader>mt",
	-- 		"<CMD>Markview toggle<CR>",
	-- 		desc = "Markview Toggle",
	-- 	},
	-- 	{
	-- 		"<leader>ms",
	-- 		"<CMD>Markview splitToggle<CR>",
	-- 		desc = "Markview Split Toggle",
	-- 	},
	-- },
}
